void bad() {
  throw new std::exception("This is how not to throw an exception");
}